catalog/urls.py
from django.urls import path
from . import views
# from django.conf.urls import url


urlpatterns = [
    path('', views.index, name='index'),
    # path('statistic/', views.statistic, name='statistic'),
    path('cars/', views.CarsListView.as_view(), name='cars'),
    path('cars/<pk>', views.CarsDetailView.as_view(), name='cars-detail'),
    path('manufacturers/', views.ManufacturersListView.as_view(), name='manufacturers'),
    path('manufacturers/<pk>', views.ManufacturersDetailView.as_view(), name='manufacturers-detail'),
    # path('mycars/', views.CarInstanceUserListView.as_view(), name='my-borrowed'),
    # path('userscars', views.CarInstanceManagerListView.as_view(), name='all-users-cars'),
    # path('cars/<pk>/renew/', views.renew_car_manager, name='renew-car-manager'),
    # path('cars/create/', views.CarCreate.as_view(), name='car-create'),
    # path('cars/<pk>/update/', views.CarUpdate.as_view(), name='car-update'),
    # path('cars/<pk>/delete/', views.CarDelete.as_view(), name='car-delete'),


]

rentcar/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic import RedirectView


urlpatterns = [
    path('admin/', admin.site.urls),
    path('catalog/', include('catalog.urls')),
    path('', RedirectView.as_view(url='/catalog/', permanent=True)),
    path('__debug__/', include('debug_toolbar.urls')),
    path('accounts/', include('django.contrib.auth.urls')),
]

catalog/models.py
from django.db import models
from django.urls import reverse
import uuid  # Required for unique car instances
from django.contrib.auth.models import User
from datetime import date




class Transmission(models.Model):
    """Model representing transmission type."""
    transmission = models.CharField(max_length=200, help_text='Enter the type of transmission')

    def __str__(self):
        return self.transmission

class CarsClass(models.Model):
    """A model that represents the car of the class."""
    name = models.CharField(max_length=200, help_text='Enter a car type (e.g. Business Class)')

    def __str__(self):
        return self.name

class Orders(models.Model):
    """Model representing the armor of a particular car"""
    # UUIDField https://docs.djangoproject.com/en/4.0/ref/models/fields/
    id = models.UUIDField(primary_key=True, default=uuid.uuid4,
                          help_text='Unique ID for this  order across whole catalog Rent Car')
    car_instance = models.ForeignKey('CarInstance', on_delete=models.SET_NULL, null=True)
    borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)
    email = models.EmailField(null=True)
    date_start = models.DateField(null=True, blank=True)
    date_finish = models.DateField(null=True, blank=True)
    place_start = models.CharField(null=True, blank=True, max_length=500)
    place_finish = models.CharField(null=True, blank=True, max_length=500)
    comments = models.CharField(null=True, max_length=5000)

    def __str__(self):
        return f'{self.id} {self.email}'



class BodyType(models.Model):
    """Model representing a body style."""
    type = models.CharField(max_length=200, help_text='Enter a car body style')

    def __str__(self):
        return self.type


class Cars(models.Model):
    """Model representing a cars (but not a specific copy of a car)."""
    model = models.CharField(max_length=200)
    manufacturers = models.ForeignKey('Manufacturers', on_delete=models.SET_NULL, null=True)
    # https://docs.djangoproject.com/en/4.0/ref/models/fields/#django.db.models.ForeignKey.on_delete
    # on_delete  определяет что делать, если удалился связанный объект
    # SET_NULL посты останутся в БД даже при удалении manufacturers,
    # но значение в поле manufacturers у постов изменится на None
    carsclass = models.ForeignKey('CarsClass', on_delete=models.SET_NULL, null=True, help_text='Choose a class for this car')
    bodytype = models.ForeignKey('BodyType', on_delete=models.SET_NULL, null=True, help_text='Select body type')
    transmission = models.ManyToManyField(Transmission, help_text='the type of transmission')
    price = models.IntegerField(null=True)

    class Meta:
        ordering = ['model', 'manufacturers']
    # https://docs.djangoproject.com/en/4.0/ref/models/options/#model-meta-options

    def get_absolute_url(self):
        return reverse('cars-detail', args=[str(self.id)])

    def display_transmission(self):
        """Creates a string for the type transmission. This is required to display type in Admin."""
        return ', '.join([transmission.transmission for transmission in self.transmission.all()[:3]])

    display_transmission.short_description = 'Type transmission'

    def __str__(self):
        return self.model


class CarInstance(models.Model):
    """Model representing a specific copy of a car (i.e. that can be rent in RentCar)."""
    # UUIDField https://docs.djangoproject.com/en/4.0/ref/models/fields/
    id = models.UUIDField(primary_key=True, default=uuid.uuid4,
                          help_text='Unique ID for this particular car across whole catelog RentCar')
    # Предотвратите удаление объекта, на который ссылаются, путем повышения RestrictedError
    # (подкласс django.db.IntegrityError). В отличие от PROTECT, удаление объекта, на который
    # указывает ссылка, разрешено, если он также ссылается на другой объект, который удаляется в той же операции,
    # но через CASCADE отношение.
    cars = models.ForeignKey('Cars', on_delete=models.RESTRICT, null=True)
    # date_start = models.DateField(null=True, blank=True)
    # date_finish = models.DateField(null=True, blank=True)
    # borrower = models.ForeignKey(User, on_delete=models.SET_NULL, null=True, blank=True)


    # LOAN_STATUS = (
    #     ('m', 'Maintenance'),
    #     ('o', 'On loan'),
    #     ('a', 'Available'),
    #     ('r', 'Reserved'),
    # )
    #
    # status = models.CharField(
    #     max_length=1,
    #     choices=LOAN_STATUS,
    #     blank=True,
    #     default='m',
    #     help_text='Car availability',
    # )

    # class Meta:
    #     ordering = ['date_start']
    #     # настройка прав доступа
    #     permissions = (("can_mark_returned", "Set car as returned"),)




    # проверка просрочена ли аренда авто
    # декоратор property позволяет добавлять метод setter
    # @property
    # def is_overdue(self):
    #     if self.date_start and date.today() > self.date_start:
    #         return True
    #     return False

    def __str__(self):
        return f'{self.cars.manufacturers} {self.cars.model}, ID:{self.id}'


class Manufacturers(models.Model):
    """Model representing a manufacturers."""
    name = models.CharField(max_length=100)
    country = models.CharField(max_length=100)

    class Meta:
        ordering = ['name', 'country']

    def get_absolute_url(self):
        return reverse('manufacturers-detail', args=[str(self.id)])

    def __str__(self):
        return self.name

catalog/forms.py
import datetime

from django import forms
from django.forms import ModelForm, DateInput

from django.core.exceptions import ValidationError
from django.utils.translation import gettext_lazy as _
from catalog.models import CarInstance


class RenewCarForm(forms.Form):
    renewal_date = forms.DateField(help_text="Enter a date between now and 4 weeks (default 3).")

    def clean_renewal_date(self):
        data = self.cleaned_data['renewal_date']

        # Check if a date is not in the past.
        if data < datetime.date.today():
            raise ValidationError(_('Invalid date - renewal in past'))

        # Check if a date is in the allowed range (+4 weeks from today).
        if data > datetime.date.today() + datetime.timedelta(weeks=4):
            raise ValidationError(_('Invalid date - renewal more than 4 weeks ahead'))

        # Remember to always return the cleaned data.
        return data


class CmsForm(forms.Form):
    title = forms.CharField(label='Ввидите заголовок', max_length=100)
    content = forms.CharField(label='Введите содержание', max_length=5000)


class FindCarsForm(forms.ModelForm):
    date_start = forms.DateField(label='Дата и время выдачи', widget=forms.DateTimeInput(
        attrs={'placeholder': 'Дата и время выдачи', 'type': 'date',}))

    date_finish = forms.DateField(label='Дата и время возврата', widget=forms.DateInput(
        attrs={'placeholder': 'Дата и время возврата', 'type': 'date',}))

    # attrs = {'class': 'form-control'}
    class Meta:
        model = CarInstance
        fields = ('date_start', 'date_finish')

catalog/views.py
from django.shortcuts import render
from .models import Transmission, CarsClass, BodyType, Cars, CarInstance, Manufacturers, Orders
from django.views import generic
from django.views.generic.detail import DetailView
from django.contrib.auth.mixins import LoginRequiredMixin, PermissionRequiredMixin
from django.shortcuts import get_object_or_404
from django.http import HttpResponseRedirect
from django.urls import reverse, reverse_lazy
import datetime
from .forms import RenewCarForm, FindCarsForm
from django.contrib.auth.decorators import permission_required
from django.db.models import Q


# @permission_required('catalog.can_mark_returned')
# def renew_car_manager(request, pk):
#     """
#     Функция просмотра для обновления определенного CarInstance менеджером
#     """
#     car_inst = get_object_or_404(CarInstance, pk=pk)
#
#     if request.method == 'POST':
#         # Создём экземпляр формы и заполняем его данными из запроса (binding):
#         form = RenewCarForm(request.POST)
#         # Check if the form is valid:
#         if form.is_valid():
#             car_inst.date_start = form.cleaned_data['renewal_date']
#             car_inst.save()
#             return HttpResponseRedirect(reverse('all-users-cars'))
#     else:
#         proposed_renewal_date = datetime.date.today() + datetime.timedelta(weeks=3)
#         form = RenewCarForm(initial={'renewal_date': proposed_renewal_date, })
#
#     return render(request, 'catalog/car_renew_manager.html', {'form': form, 'carinst': car_inst})


def search_free_cars(form_date_start: datetime, form_date_finish: datetime):
    ''' Возвращает список моделей автомобилей которые свободны в эти даты'''
    free_car_instance: list = []
    cars = Cars.objects.all() # все авто
    for car in cars: # берем каждое авто
        for carinstance in car.carinstance_set.all(): # получаем все экземпляры этого авто и проходим по каждому
            orders = Orders.objects.filter(car_instance=carinstance) # полчаем сет заказов для конкретного экземпляра авто
            if len(orders) == 0:  # если нет заказов, добавляем экземпляр и переходим к следующему
                free_car_instance.append(carinstance)
                continue
            # проверяем свобен ли экземпляр авто в принятые даты
            for order in orders:
                order_date_start = order.date_start
                order_date_finish = order.date_finish
                latest_start = max(order_date_start, form_date_start)
                earliest_finish = min(order_date_finish, form_date_finish)
                if latest_start > earliest_finish:
                    free_car_instance.append(carinstance)
                    break
    # модели авто у которых есть свободные экземпляры на указанные даты
    free_car = set([car_instance.cars for car_instance in free_car_instance ])
    return free_car

def is_valid_custom(form_date_start, form_date_finish):
    errors = []
    if form_date_start > form_date_finish:
        errors.append('Дата начала аренды должна быть раньше даты конца аренды.')
    if form_date_start < datetime.date.today():
        errors.append('Извините, пока мы не можем отправить машину в прошлое.')
    return errors



def index(request):
    """
    Функция отображения для домашней страницы сайта.
    """
    # форма поиска автомобиля
    errors = []
    free_cars = []
    if request.method == 'POST':
        user_form = FindCarsForm(request.POST)
        if user_form.is_valid():
            errors = is_valid_custom(user_form.cleaned_data["date_start"], user_form.cleaned_data["date_finish"])
            if len(errors) == 0:
                free_cars = search_free_cars(user_form.cleaned_data["date_start"], user_form.cleaned_data["date_finish"])
            return render(request, 'index.html', {'user_form': user_form,
                                              'errors': errors,
                                              'free_cars': free_cars})
    user_form = FindCarsForm()
    # Отрисовка HTML-шаблона index.html с данными внутри
    return render(request, 'index.html', {'user_form': user_form, 'errors': errors})

    # Отрисовка HTML-шаблона index.html с данными внутри
    # переменной контекста context

# def statistic(request):
#     # Генерация "количеств" некоторых главных объектов
#     # https://docs.djangoproject.com/en/4.0/ref/models/querysets/#field-lookups
#     num_cars = Cars.objects.all().count()
#     num_instances = CarInstance.objects.all().count()
#     num_manufacturers = Manufacturers.objects.count()  # Метод 'all()' применён по умолчанию.
#     # Number of visits to this view, as counted in the session variable.
#     num_visits = request.session.get('num_visits', 0)
#     request.session['num_visits'] = num_visits + 1
#     context = {'num_cars': num_cars,
#                'num_instances': num_instances,
#                'num_manufacturers': num_manufacturers,
#                'num_visits': num_visits }
#
#     # Отрисовка HTML-шаблона index.html с данными внутри
#     return render(request, 'catalog/statistic.html', context)


# https://docs.djangoproject.com/en/4.0/topics/class-based-views/generic-display/
class CarsListView(generic.ListView):
    model = Cars
    paginate_by = 10
    # template_name = 'catalog/cars.html'


class CarsDetailView(generic.DetailView):
    model = Cars
    paginate_by = 10

#
# class CarInstanceUserListView(LoginRequiredMixin, generic.ListView):
#     """
#     Общий список автомобилей предоставленных в аренду текущему пользователю.
#     """
#     model = CarInstance
#     template_name = 'catalog/carinstance_list_borrowed_user.html'
#     paginate_by = 10
#
#     def get_queryset(self):
#         return CarInstance.objects.filter(borrower=self.request.user).filter(status__exact='o').order_by('date_start')
#
#
# class CarInstanceManagerListView(PermissionRequiredMixin, generic.ListView):
#     """
#     Общий список автомобилей предоставленных в аренду всем пользователям.
#     """
#     model = CarInstance
#     permission_required = 'catalog.can_mark_returned'
#     template_name = 'catalog/carinstance_list_borrowed_manager.html'
#     paginate_by = 10
#
#     def get_queryset(self):
#         return CarInstance.objects.filter(status__exact='o').order_by('date_start')


class ManufacturersListView(generic.ListView):
    model = Manufacturers
    paginate_by = 10


class ManufacturersDetailView(generic.DetailView):
    model = Manufacturers
    paginate_by = 10


# from django.views.generic.edit import CreateView, UpdateView, DeleteView
# from catalog.models import Cars


# https://docs.djangoproject.com/en/4.0/ref/class-based-views/generic-editing/
# class CarCreate(PermissionRequiredMixin, CreateView):
#     model = Cars
#     fields = ['model', 'manufacturers', 'transmission', 'bodytype', ]
#     initial = {'bodytype': 'sport'}
#     permission_required = 'catalog.can_mark_returned'
#
#
# class CarUpdate(PermissionRequiredMixin, UpdateView):
#     model = Cars
#     fields = ['model', 'manufacturers', 'transmission', 'bodytype', ]
#     permission_required = 'catalog.can_mark_returned'
#
#
# class CarDelete(PermissionRequiredMixin, DeleteView):
#     model = Cars
#     success_url = reverse_lazy('cars')  # редирект на страницу cars/
#     permission_required = 'catalog.can_mark_returned'

catalog/templates/catalog/car_renew_manager.html
{% extends "base_generic.html" %}
{% block content %}

    <h1>Renew: {{carinst.book.title}}</h1>
    <p>Borrower: {{carinst.borrower}}</p>
    <p {% if carinst.is_overdue %} class="text-danger"{% endif %}>Due date: {{carinst.date_start}}</p>

    <form action="" method="post">
        {% csrf_token %}
        <table>
        {{ form }}
        </table>
        <input type="submit" value="Submit" />
    </form>

{% endblock %}

catalog/templates/catalog/carinstance_list_borrowed_manager.html
{% extends "base_generic.html" %}

{% block content %}
    <h1/>Все автомобили в аренде.</h1>
    {% if perms.catalog.can_mark_returned %}
        {% for carinstance in carinstance_list %}
            <hr>
            <p>{{ carinstance.cars.manufacturers }}
               {{ carinstance.cars.model }}
               ({{ carinstance.date_start }})
               {{ carinstance.borrower }}
               {% if carinstance.is_overdue %}
               <mark style="color: red">срок аренды истек!</mark></p>
               {% endif %}
        {% endfor %}
    {% else %}
    <p>Автомобилий нет</p>
    {% endif %}

{% endblock %}

catalog/templates/catalog/carinstance_list_borrowed_user.html
{% extends "base_generic.html" %}

{% block content %}
    <h1/>Арендуемые автомобили</h1>

    {% if carinstance_list %}
    <ul>

      {% for сarinstance in carinstance_list %}
      <li class="{% if сarinstance.is_overdue %}text-danger{% endif %}">
        <a href="{% url 'cars-detail' сarinstance.cars.pk %}">
            {{сarinstance.cars.model}}
        </a> ({{ сarinstance.date_start }})
      </li>
      {% endfor %}
    </ul>

    {% else %}
      <p>Нет арендованных автомобилей.</p>
    {% endif %}
{% endblock %}

catalog/templates/catalog/cars_confirm_delete.html
{% extends "base_generic.html" %}
{% block content%}
<p>Вы хотите удалить автомобиль из базы даных? {{ cars.manufacturers }}{{ cars.model }}</p>
<form action="" method="post">
    {% csrf_token %}
    <table>
        {{ form.as_table }}
    </table>
    <input type="submit" value="Delete">
</form>
{% endblock %}

catalog/templates/catalog/cars_detail.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Информация об автомобиле</h1>

{% if object %}
<ul>
    <li>{{ cars.manufacturers }} {{ cars.model }}</li>
    <li>{{ object.carsclass }}</li>
    <li>{{ object.bodytype }}</li>
    <li>Трансмиссия:
        {% for transmission in cars.transmission.all %}
        {{ transmission }}
        {% if not forloop.last %},
        {% endif %}
        {% endfor %}
    </li>
</ul>
<div style="margin-left:20px;margin-top:20px">
    <h4>Автомобили в наличии:</h4>
<!--    reverse lookup  cars.carinstance_set.all -->
<!--    text-success a-->
<!--    text-danger d-->
<!--    text-warning-->
<!--    Due to be returned:-->
<!--    text-muted-->
    {% for copy in cars.carinstance_set.all %}
        <hr>
        <p class="{{ {% if copy.status == 'a' %}text-success{% elif copy.status == 'd' %}text-danger{% else %}text-warning{% endif %}
        }}">
            {{ copy.get_status_display }}</p>
        {% if copy.status != 'a' %}
        <p>дата возврата: {{ copy.date_start }}</p>
        {% endif %}
        <p>{{ copy.id }}</p>
    {% endfor %}

</div>

{% else %}
<p>Автомобилей пока нет.</p>
{% endif %}
{% endblock %}

catalog/templates/catalog/cars_form.html
{% extends "base_generic.html" %}

{% block content %}
  <form action="" method="post">
    {% csrf_token %}
    <table>
    {{ form.as_table }}
    </table>
    <input type="submit" value="Submit">
  </form>
{% endblock %}

catalog/templates/catalog/cars_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Автомобли</h1>

    {% if cars_list %}
    <ul>
      {% for car in cars_list %}
      <li>
        <a href="{{ car.get_absolute_url }}">{{ car.model }}</a> ({{ car.manufacturers }})
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>Автомобилей пока нет.</p>
    {% endif %} 
{% endblock %}

catalog/templates/catalog/manufacturers_detail.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Информация об производители</h1>

{% if object %}

<h2>{{ manufacturers.name }} {{ manufacturers.country }}</h2>

<div style="margin-left:20px;margin-top:20px">
    <h4>Автомобили производителя в наличии:</h4>
    <!--    reverse lookup  cars.carinstance_set.all -->
    <!--    text-success a-->
    <!--    text-danger d-->
    <!--    text-warning-->
    <!--    Due to be returned:-->
    <!--    text-muted-->
    {% for copy in manufacturers.cars_set.all %}
    <hr>
    <p>{{ copy.model }}</p>
    {% endfor %}

</div>

{% else %}
<p>Автомобилей пока нет.</p>
{% endif %}
{% endblock %}

catalog/templates/catalog/manufacturers_list.html
{% extends "base_generic.html" %}

{% block content %}
    <h1>Бренды автомобилей</h1>
    {% if manufacturers_list %}
    <ul>
      {% for manufacturer in manufacturers_list %}
      <li>
<!--           manufacturer.get_absolute_url  -->
        <a href="{{ manufacturer.get_absolute_url }}">{{ manufacturer.name }}</a> ({{ manufacturer.country }})
      </li>
      {% endfor %}

    </ul>
    {% else %}
      <p>Брендов пока нет.</p>
    {% endif %}
{% endblock %}

catalog/templates/catalog/statistic.html
{% extends "base_generic.html" %}

{% block content %}
<h1>Динамический контент</h1>
  <p>В сервисе проката автомобилей имеется следующее количество записей:</p>
  <ul>
    <li><strong>Автомобилей:</strong> {{ num_cars }}</li>
    <li><strong>Экземпляров автомобилей:</strong> {{ num_instances }}</li>
    <li><strong>Доступно сейчас:</strong> {{ num_instances_available }}</li>
    <li><strong>Количество представленных брендов:</strong> {{ num_manufacturers }}</li>
    <li><strong>Количество визитов:</strong> {{ num_visits }}</li>
  </ul>

{% endblock %}